# Generated by Django 5.2.7 on 2025-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['ordem', 'data_vencimento']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
